// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/denbeigh2000/crawly (interfaces: Crawler)

package mock_crawly

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Crawler interface
type MockCrawler struct {
	ctrl     *gomock.Controller
	recorder *_MockCrawlerRecorder
}

// Recorder for MockCrawler (not exported)
type _MockCrawlerRecorder struct {
	mock *MockCrawler
}

func NewMockCrawler(ctrl *gomock.Controller) *MockCrawler {
	mock := &MockCrawler{ctrl: ctrl}
	mock.recorder = &_MockCrawlerRecorder{mock}
	return mock
}

func (_m *MockCrawler) EXPECT() *_MockCrawlerRecorder {
	return _m.recorder
}

func (_m *MockCrawler) Crawl(_param0 string) ([]string, error) {
	ret := _m.ctrl.Call(_m, "Crawl", _param0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCrawlerRecorder) Crawl(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Crawl", arg0)
}
